Added GRS, replica, storage auto-grow, added CRLF to .kql
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #146
Opened 2024-05-22 15:20 UTC by mspetroula

# Overview/Summary

Added GRS, replica, storage auto-grow to both PostgreSQL and MySQL added CRLF to .kql because validation was failing in the Lint phase

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1.	Modified: azure-resources/DBforMySQL/flexibleServers/recommendations.yaml
2.	Modified: azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml
3.	Added azure-resources/DBforMySQL/flexibleServers/kql/5c96afc3-7d2e-46ff-a4c7-9c32850c441b.kql
4.	Added azure-resources/DBforMySQL/flexibleServers/kql/8176a79d-8645-4e52-96be-a10fc0204fe5.kql
5.	Added azure-resources/DBforMySQL/flexibleServers/kql/b49a8653-cc43-48c9-8513-a2d2e3f14dd1.kql
6.	Added azure-resources/DBforPostgreSQL/flexibleServers/kql/2ab85a67-26be-4ed2-a0bb-101b2513ec63.kql
7.	Added azure-resources/DBforPostgreSQL/flexibleServers/kql/31f4ac4b-29cb-4588-8de2-d8fe6f13ceb3.kql
8.	Added azure-resources/DBforPostgreSQL/flexibleServers/kql/6293a3cc-6b4a-4c0f-9ea7-b8ae8d7dd3d5.kql
9.	Modified modified:   azure-resources/DBforMySQL/flexibleServers/kql/82a9a0f2-24ee-496f-9ad2-25f81710942d.kql
10.	Modified:   azure-resources/DBforMySQL/flexibleServers/kql/88856605-53d8-4bbd-a75b-4a7b14939d32.kql        
11.	Modified:   azure-resources/DBforPostgreSQL/flexibleServers/kql/b2bad57d-7e03-4c0f-9024-597c9eb295bb.kql
12.	 Modified:   azure-resources/DBforPostgreSQL/flexibleServers/kql/ca87914f-aac4-4783-ab67-82a6f936f194.kql

### Breaking Changes

1. _Replace me_
2. _Replace me_

## As part of this pull request I have

- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x ] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/ace06300-6a65-4220-8a63-b34a28023a29)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/abe5e518-06f7-4b73-8ebe-9dd0ec1b435c)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/191a3061-c942-468e-9553-45283a97e43d)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/9ce40521-de68-407e-a446-bb400dccf78e)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/42f85255-076b-449a-818a-e5ebed2b11d6)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/d43556d4-9529-4845-8201-daac4d62d59e)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/a9b2ca09-60c6-4076-801d-56cf3c03ca84)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/88e310f6-f9c5-418f-9799-0fcd2dc170c7)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/abf62a2a-eece-4db6-be56-08f26b26e108)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/0a1688dd-da84-46e1-b30c-84638238db45)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/ae16cf4a-2ff0-4a5c-80e1-f082f5086183)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/2c727dba-3fda-4f1a-9377-873c5934bf84)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/775dfea9-40c2-4101-9ecb-24442591bdf8)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/9c037a88-9c13-4675-90db-99aadfdcf78d)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/0c97cd22-b84c-45e0-a1e3-282d171cd0ef)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/b828d98f-2e49-4c88-95fc-a20adb194d02)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/ea3b40d5-b467-4795-87a7-5f988644bf15)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/72a9f784-7f6d-4157-ad31-19165fe49bef)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/a0a0bfb6-4f11-468f-b731-89484fb7af11)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/13f34609-6d44-4e9d-bc6c-fa09c901ddd4)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/c2fcb94c-1ec1-4e54-8cf4-0fce33e73e7d)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/e145a2fd-26ed-4bcb-9890-fe67673e98de)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/f3a9b5aa-497f-4f99-8357-8e0ab1fe3fd8)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/104512191/f3ba5646-9301-4aae-a344-c9642a8f8338)

- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-05-22 16:28 UTC, ejhenry reviewed
Thanks for the contribution @mspetroula. Just a few minor edits.

2024-05-22 16:28 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/kql/6293a3cc-6b4a-4c0f-9ea7-b8ae8d7dd3d5.kql
> +// Azure Resource Graph Query
```suggestion
// cannot-be-validated-with-arg
```

2024-05-22 16:28 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/kql/6293a3cc-6b4a-4c0f-9ea7-b8ae8d7dd3d5.kql
> +// Find Database for PostgreSQL instances that do not have a storage auto-grow
```suggestion

```

2024-05-22 16:28 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/kql/6293a3cc-6b4a-4c0f-9ea7-b8ae8d7dd3d5.kql
> +// auto-grow property not available today in the output
```suggestion

```

2024-05-22 16:28 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/kql/6293a3cc-6b4a-4c0f-9ea7-b8ae8d7dd3d5.kql
> +// No query available at the moment
```suggestion

```

2024-05-22 16:28 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml
> +  automationAvailable: arg
```suggestion
  automationAvailable: no
```

2024-05-23 00:59 UTC, ejhenry requested changes
Edits to potentialBenefits to meet 60 character limit requirement

2024-05-23 00:59 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml
> +      url: "https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-auto-grow-storage-portal"
```suggestion
      url: "https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-auto-grow-storage-portal"
      
```

2024-05-23 00:59 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml
> +  potentialBenefits: Scale storage automatically to accomodate increasing workloads
```suggestion
  potentialBenefits: Scale storage automatically to meet increasing demand
```

2024-05-23 00:59 UTC, ejhenry commented on azure-resources/DBforMySQL/flexibleServers/recommendations.yaml
> +  potentialBenefits: Scale storage automatically to accomodate increasing workloads
```suggestion
  potentialBenefits: Scale storage automatically to meet increasing demand
```

2024-05-23 01:03 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml
> +
```suggestion

```

2024-06-07 20:31 UTC, ejhenry commented on azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml
> +      url: "https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-auto-grow-storage-portal"
```suggestion
      url: "https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-auto-grow-storage-portal"

```

2024-06-07 20:36 UTC, ejhenry approved these changes
LGTM

2024-06-12 20:33 UTC, oZakari approved these changes
LGTM 👍🏼

2024-06-13 18:44 UTC, merged