Update recommendations.yaml
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #153
Opened 2024-05-23 17:26 UTC by bkaage

Updated by Bkaage on 5/23/24

# Overview/Summary

Updated content in Key Vault recommendations. Added 1 new recommendation, Removed Soft Delete and marked all as PG Verified - True

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. _Replace me_
2. _Replace me_

### Breaking Changes

1. _Replace me_
2. _Replace me_

## As part of this pull request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-05-23 21:06 UTC, Dost2010 commented
@bkaage  | limit potentialbenefit field is 60 characters. For more information please refer to contribution guide --> https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing/create-content/create-recommendations/

2024-05-23 21:08 UTC, oZakari requested changes

2024-05-23 21:08 UTC, oZakari commented on azure-resources/KeyVault/vaults/recommendations.yaml
> +- description: Azure Key Vault RBAC for Data Plane
Could you please remove the soft-delete kql file and then add a new kql file with the new recommendation guide.

2024-05-23 21:16 UTC, oZakari commented on azure-resources/KeyVault/vaults/recommendations.yaml
> +    Enhances security by integrating with Azure RBAC, replacing the legacy Access Policy model.
```suggestion
   Boosts security by integrating with Azure RBAC, replacing Access Policy
```

Needs to be less than 60 characters

2024-05-31 15:24 UTC, bkaage commented
Please review

2024-05-31 21:44 UTC, oZakari commented on azure-resources/KeyVault/vaults/recommendations.yaml
> +- description: Azure Key Vault RBAC for Data Plane
It doesn't look like the KQL file was removed for soft delete. There also wasnt a new query file added for the new data plane recommendation.

Also, could you please reach out to me in Teams (ztrocinski) so I can confirm your Microsoft alias.

2024-06-17 09:56 UTC, closed without merging