Reliability in Azure Container Apps Environments. Check for AZ deployment
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #170
Opened 2024-05-29 12:54 UTC by henrikwh

# Overview/Summary

Adds check AZ for Container App Environment. 
Docs already mentions AZ should be enabled for container apps enviroinments.

## As part of this pull request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/1696278/c8c53013-4b53-4381-a2f5-3a87465b078e)

- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-05-29 20:00 UTC, Dost2010 requested changes
The two recommendations seem to be duplicate of each other, both have only one link in reference and they both serve the same purpose. I suggest creating combining it to one and also simplify query to a level where its actionable by end user

2024-05-29 20:00 UTC, Dost2010 commented on azure-resources/App/containerApps/kql/e2a624d7-ce3e-4cd6-abe2-4635a78ec9de.kql
Hello, based on the documentation on this link https://learn.microsoft.com/en-us/azure/reliability/reliability-azure-container-apps?tabs=azure-cli , only zoneRedundant": true. should be sufficient enough to enable zone redundancy for container app. Counting replica (minreplicas/maxreplica) add complexity to query.  Isnt it the case that making zoneRedundant": true. would automatically create replicas and distribute it across zone?

2024-05-30 06:36 UTC, henrikwh commented on azure-resources/App/containerApps/kql/e2a624d7-ce3e-4cd6-abe2-4635a78ec9de.kql
Let me merge into one rule.

They are for sure related, but actions required are different. First ensure that Container app environment have AZ enabled. I dont see an upgrade path, besides deploying a new CAE. The next inspects all container apps, ensure that theres more replicas to leverage AZs. To mitigate here, its just a new replica deployment.

Note in doc "There is no extra charge for enabling zone redundancy, but it only provides benefits when you have 2 or more replicas, with 3 or more being ideal since most regions that support zone redundancy have 3 zones."

2024-05-30 18:10 UTC, ejhenry reviewed
Thanks for the contribution @henrikwh! Please include a screenshot in this PR of your successful testing of the ARG query.

2024-05-31 15:32 UTC, ejhenry approved these changes
LGTM 👍

2024-05-31 21:35 UTC, oZakari approved these changes

2024-05-31 21:35 UTC, oZakari commented on azure-resources/App/managedEnvironments/recommendations.yaml
> +    To take advantage of availability zones, you must enable zone redundancy when you create a Container Apps environment. The environment must include a virtual network with an available subnet. To
```suggestion
    To take advantage of availability zones, you must enable zone redundancy when you create a Container Apps environment. The environment must include a virtual network with an available subnet. To ensure proper distribution of replicas, set your app's minimum replica count to three.
```

2024-05-31 23:15 UTC, merged