SAP recommendations added
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #318
Opened 2024-07-29 03:35 UTC by humblejay

# Overview/Summary

SAP Netapp files & Storage related recommendations added

## Related Issues/Work Items

AB#36151

### Breaking Changes

None

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-07-31 22:37 UTC, ejhenry commented on azure-specialized-workloads/sap/kql/.kql
@humblejay was the addition of this file unintentional? If so, please remove from the PR

2024-07-31 22:38 UTC, ejhenry commented
@Azure/aprl-sap please review

2024-08-01 16:36 UTC, humblejay commented on azure-specialized-workloads/sap/kql/.kql
removed, that was unintentional

2024-08-02 08:14 UTC, PmeshramPM reviewed
Hi @humblejay - On the links for ANF , please use these ones. These links have the Cluster parameter when you are using ANF for SUSE or RHEL clusters. 

https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-nfs-simple-mount?tabs=lb-portal%2Censa1

https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-nfs-simple-mount?tabs=lb-portal%2Censa1

https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-netapp-files?tabs=lb-portal%2Censa1


https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-netapp-files?tabs=lb-portal%2Censa1

https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-rhel-netapp-files?tabs=lb-portal%2Censa1

https://learn.microsoft.com/en-us/azure/sap/workloads/sap-hana-high-availability-netapp-files-red-hat?tabs=lb-portal

https://learn.microsoft.com/en-us/azure/sap/workloads/sap-hana-high-availability-netapp-files-suse?tabs=lb-portal

2024-08-20 20:58 UTC, ejhenry commented
@Azure/aprl-sap please review

2024-08-21 16:27 UTC, oZakari requested changes

2024-09-02 11:05 UTC, PmeshramPM approved these changes
approved

2024-09-04 19:56 UTC, merged