fix arg code for PostgreSQL read replica detection
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #430
Opened 2024-09-24 09:41 UTC by jdmsoss

# Overview/Summary

Initial ARG code "Find Database for PostgreSQL instances that are read replicas" but we're looking for "Database for PostgreSQL instances that do not have read replicas".

## As part of this pull request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-09-30 17:22 UTC, oZakari requested changes
Thanks for these improvements @jdmsoss! When you have a chance, could you share a screenshot of the query showing the correct results please?

2024-10-03 12:48 UTC, jdmsoss commented
> Thanks for these improvements @jdmsoss! When you have a chance, could you share a screenshot of the query showing the correct results please?

Please see my screenshots in my initial comment.

2024-10-03 20:07 UTC, oZakari approved these changes

2024-10-08 22:40 UTC, ejhenry approved these changes
LGTM thanks @jdmsoss!

2024-10-08 22:44 UTC, merged