fix: exclude master DB from failover group recommendation
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #469
Opened 2024-10-17 15:17 UTC by jdmsoss

# Overview/Summary

Master database should be excluded from "Auto Failover Groups can encompass one or multiple databases, usually used by the same app." recommendation result.

Before my fix 👇

![before](https://github.com/user-attachments/assets/52c5b4ad-08c6-4c96-a6ef-9d983f922541)

After my fix 👇

![after](https://github.com/user-attachments/assets/940733c3-8b15-4e6e-bc68-6be1d321b786)

## As part of this pull request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [X] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-10-21 03:40 UTC, oZakari approved these changes
LGTM

2024-10-23 03:08 UTC, ramyerrabotu requested changes

2024-10-23 03:08 UTC, ramyerrabotu commented on azure-resources/Sql/servers/kql/943c168a-2ec2-a94c-8015-85732a1b4859.kql
>  // Azure Resource Graph Query
```suggestion
// Azure Resource Graph Queries 
```

2024-10-23 03:10 UTC, ramyerrabotu approved these changes

2024-10-23 03:11 UTC, ramyerrabotu commented
Good to exclude the master DB

2024-10-23 03:12 UTC, merged