fix: build-recommendation-object.yml workflow
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #477
Opened 2024-10-22 17:08 UTC by kpoineal

# Overview/Summary

Updated Recommendation Object creation to be done as part of PR validation and included in new changes.

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-10-22 17:33 UTC, oZakari requested changes

2024-10-22 17:33 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> +    contents: write
```suggestion
    contents: read
```

2024-10-22 17:33 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> +    contents: write
Scope permissions at job level

2024-10-22 17:33 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> -  build:
update-json-object

2024-10-22 17:33 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> +      uses: actions/checkout@v3
```suggestion
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
```

2024-10-22 17:33 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> +      uses: actions/checkout@v3
Best practice to use commit sha of action. Also v4 is latest.

2024-10-22 17:34 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> +  Generate-Documentation:
```suggestion
  update-json-object:
```

2024-10-22 18:17 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> +    contents: read
```suggestion
   contents: read
```

2024-10-22 18:18 UTC, oZakari commented on .github/workflows/build-recommendation-object.yml
> +   contents: read
```suggestion
  contents: read
```

2024-10-22 18:18 UTC, oZakari approved these changes

2024-10-24 17:41 UTC, ejhenry approved these changes

2024-10-24 17:42 UTC, merged