Aprlvwanv2
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #566
Opened 2024-12-11 15:41 UTC by maurojasmsft

# Overview/Summary

Adding ARG queries for APRL recommendations vWAN.
-	Monitor health for v-Hub's ExpressRoute gateway  
- -	Monitor health for v-Hubs 
- -	Monitor gateway for Site-to-site v-Hub's VPN gateway 
- -	Monitor health for v-Hub's Point-to-Site VPN gateways 

Added new recommendations and KQL queries

- Configure diverse VPN Site links to different VPN concentrators on-premises.
- -	Avoid using ExpressRoute circuits for VNet to VNet communication 
- -	Migrate from Basic to Standard Virtual WAN

## Related Issues/Work Items

### Breaking Changes

1. _Replace me_
2. _Replace me_

## As part of this pull request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x ] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-12-11 16:44 UTC, ehaslett commented on azure-resources/Network/expressRouteGateways/recommendations.yaml
> +  potentialBenefits: Shortest path between VNETs. Avoids hairpinning traffic through on-premises.
I wonder if "... through on-premises." should be rewritten as "... through Microsoft edge." or similar.

2024-12-11 16:45 UTC, ehaslett submitted a review, later dismissed
Other than one comment I made, LGTM

2024-12-12 23:07 UTC, DaFitRobsta approved these changes
Fix the output from the KQL to follow the guidelines outlined here:
https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing/create-content/create-arg-queries/
Then it will LGTM 👍.

2024-12-16 22:04 UTC, oZakari approved these changes
Nice work @maurojasmsft!

2024-12-18 19:12 UTC, rodrigosantosms commented on azure-resources/Network/vpnSites/recommendations.yaml
Add the following to the end of the "Description" --> (Non Mission-Critical workloads only)

For example: Deploy active-active VPN concentrators on your premises (Non Mission-Critical workloads only)

Make sure the description does not exceed 100Chars.

2024-12-18 19:13 UTC, rodrigosantosms requested changes
Please change the recommendation for VpnSites.

Add the following to the end of the "Description" --> (Non Mission-Critical workloads only)

For example: Deploy active-active VPN concentrators on your premises (Non Mission-Critical workloads only)

Make sure the description does not exceed 100Chars.

2025-01-10 15:56 UTC, ejhenry commented
@Azure/aprl-networking please review

2025-01-22 20:32 UTC, ehaslett approved these changes
LGTM. Tested every query except one and they all work great - nice work!

2025-01-22 20:36 UTC, merged