Added AI Search resiliency recommendations
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #584
Opened 2024-12-18 07:47 UTC by ripadrao

# Overview/Summary

## Related Issues/Work Items

### Breaking Changes

1. _Replace me_
2. _Replace me_

## As part of this pull request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-12-18 19:28 UTC, rodrigosantosms commented on azure-resources/CognitiveServices/AIsearch/kql/dff62efe-c3a3-4621-98b3-c877c65cb195.kql
Please follow the standards defined for ARGs, all ARGs should project the same properties with the same names in the same order. https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing/create-content/create-arg-queries/

2024-12-18 19:30 UTC, rodrigosantosms commented on azure-resources/CognitiveServices/AIsearch/recommendations.yaml
I'd suggest changing the recommendationControl to HighAvailability. All Zone redundancy related are being associated with it.

2024-12-18 19:31 UTC, rodrigosantosms requested changes
Please review comments for each file.

2024-12-19 08:24 UTC, ripadrao commented on azure-resources/CognitiveServices/AIsearch/recommendations.yaml
updated

2024-12-19 10:33 UTC, ripadrao commented on azure-resources/CognitiveServices/AIsearch/kql/dff62efe-c3a3-4621-98b3-c877c65cb195.kql
please confirm kql are correct

2024-12-19 10:33 UTC, ripadrao commented on azure-resources/CognitiveServices/AIsearch/kql/b376281d-bfec-4695-8f90-9a44544fdfa4.kql
done, please confirm

2024-12-20 15:58 UTC, oZakari commented on azure-resources/CognitiveServices/AIsearch/kql/b376281d-bfec-4695-8f90-9a44544fdfa4.kql
Can you please include screenshots of the output confirming that it is working as anticipated?

2025-01-04 07:13 UTC, closed without merging

2025-01-07 09:32 UTC, ripadrao reviewed
Updated images of kql