New Aprl recommendations for CognitiveServices/Accounts & MachineLearningservices/Workspaces
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #585
Opened 2024-12-18 08:44 UTC by Poven795909

# Overview/Summary

> Added new APRL recommendations under CognitiveServices/accounts and MachineLeaningservices/workspaces
> Cross-referenced the recommendations in "Artificial Intelligence" under specialized workloads section.

## Related Issues/Work Items

Fixes AB#38701
Fixes AB#38702
Fixes AB#38704

### Breaking Changes

No breaking changes

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-12-18 19:21 UTC, rodrigosantosms requested changes
Please review recommendations below:

- Recommendation: Use comprehensive monitoring solution for AOAI service
High impact is something that will directly help increase the resiliency, all monitoring related recommendations today are Medium or Low. I'd suggest we move this to Medium.

- Recommendation: "Tune AOAI content filters to ensure requests are properly filtered" 
It does not seem to help increase resiliency, it seems Security/Content governance control, and probably the right place would be in Defender for Cloud or Advisor (under Security, which is again managed by Defender for Cloud team).

2024-12-19 04:11 UTC, Poven795909 commented
> Please review recommendations below:
> 
> * Recommendation: Use comprehensive monitoring solution for AOAI service
>   High impact is something that will directly help increase the resiliency, all monitoring related recommendations today are Medium or Low. I'd suggest we move this to Medium.
> * Recommendation: "Tune AOAI content filters to ensure requests are properly filtered"
>   It does not seem to help increase resiliency, it seems Security/Content governance control, and probably the right place would be in Defender for Cloud or Advisor (under Security, which is again managed by Defender for Cloud team).

I have corrected the priority to "medium" for monitoring recommendation. For the second point, I have opened an internal teams chat for discussion.

2025-01-06 19:12 UTC, oZakari approved these changes
Content and changes LGTM, thanks you @Poven795909! Can you just need to update the merge conflicts before we can merge it.

2025-01-07 04:01 UTC, Poven795909 commented
> Content and changes LGTM, thanks you @Poven795909! Can you just need to update the merge conflicts before we can merge it.

Hi @oZakari , I have resolved the merge conflicts.

2025-01-08 02:22 UTC, Poven795909 reviewed
changes included

2025-01-08 03:36 UTC, ejhenry approved these changes
LGTM

2025-01-08 16:07 UTC, merged