docs: Added new recommendations for Azure bastion hosts
Azure/Azure-Proactive-Resiliency-Library-v2 pull request #586
Opened 2024-12-18 11:33 UTC by sonmitt

# Overview/Summary

Added new recommendations for Azure bastion hosts and cross referenced them in dependent resource section in Specialized workload/AI

## Related Issues/Work Items

https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38508/

## As part of this pull request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-12-18 19:25 UTC, rodrigosantosms requested changes
- Recommendation: "Deploy Azure Bastion across Availability Zones"
I suggest we move this recommendation from High to Medium, since Bastion is not directly used by workloads, it is an important component that allows admins to access their environments for troubleshooting, but deploying a bastion in a zone redundant config would not directly increase the resilience of the workload.

For example, if they do not deploy a Load Balancer across zones and a Zone goes down, it will have direct effect on the workload, while Bastion would not.

2024-12-19 03:38 UTC, sonmitt commented
Thanks Rodrigo. Make sense to make the impact as Medium. I will do the changes.

2024-12-19 05:37 UTC, sonmitt commented
Review comment has been addressed.

2025-01-06 19:19 UTC, oZakari approved these changes
LGTM

2025-01-13 04:40 UTC, sonmitt commented
@rodrigosantosms, proposed changes have been done. Please approve the PR.

2025-01-15 01:22 UTC, ejhenry commented
@sonmitt please resolve the conflicts

2025-01-15 07:29 UTC, sonmitt commented
@oZakari and @ejhenry, I resolved the merge conflicts. Looks like it need approvals again.

2025-01-16 01:32 UTC, ejhenry approved these changes
LGTM

2025-01-16 01:32 UTC, merged